package export

import (
	"fmt"
	"os"
	"strings"
	"time"

	"portscango/internal/scanner"
)

// MarkdownReport markdown report data
type MarkdownReport struct {
	Target     string
	IP         string
	TotalPorts int
	OpenPorts  int
	ScanTime   string
	Results    []scanner.Result
	OS         string
	VulnCount  int
}

// WriteMarkdown exports results to Markdown file
func WriteMarkdown(filename string, report MarkdownReport) error {
	var sb strings.Builder

	// Header
	sb.WriteString("# 🔍 PortScanGO Scan Report\n\n")
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	// Badges
	sb.WriteString("![Version](https://img.shields.io/badge/PortScanGO-v4.0-blue) ")
	if report.OpenPorts > 0 {
		sb.WriteString(fmt.Sprintf("![Open Ports](https://img.shields.io/badge/Open_Ports-%d-green) ", report.OpenPorts))
	} else {
		sb.WriteString("![Open Ports](https://img.shields.io/badge/Open_Ports-0-red) ")
	}
	if report.VulnCount > 0 {
		sb.WriteString(fmt.Sprintf("![Vulnerabilities](https://img.shields.io/badge/Vulnerabilities-%d-red)", report.VulnCount))
	} else {
		sb.WriteString("![Vulnerabilities](https://img.shields.io/badge/Vulnerabilities-0-brightgreen)")
	}
	sb.WriteString("\n\n")

	// Summary
	sb.WriteString("## 📊 Summary\n\n")
	sb.WriteString("| Property | Value |\n")
	sb.WriteString("|----------|-------|\n")
	sb.WriteString(fmt.Sprintf("| **Target** | `%s` |\n", report.Target))
	if report.IP != "" {
		sb.WriteString(fmt.Sprintf("| **IP Address** | `%s` |\n", report.IP))
	}
	sb.WriteString(fmt.Sprintf("| **Ports Scanned** | %d |\n", report.TotalPorts))
	sb.WriteString(fmt.Sprintf("| **Open Ports** | %d |\n", report.OpenPorts))
	sb.WriteString(fmt.Sprintf("| **Scan Duration** | %s |\n", report.ScanTime))
	if report.OS != "" {
		sb.WriteString(fmt.Sprintf("| **Detected OS** | %s |\n", report.OS))
	}
	sb.WriteString("\n")

	// Open Ports Table
	if len(report.Results) > 0 {
		sb.WriteString("## 🔓 Open Ports\n\n")
		sb.WriteString("| Port | State | Service | Banner |\n")
		sb.WriteString("|------|-------|---------|--------|\n")

		for _, r := range report.Results {
			banner := r.Banner
			if len(banner) > 40 {
				banner = banner[:40] + "..."
			}
			// Escape pipe characters
			banner = strings.ReplaceAll(banner, "|", "\\|")
			sb.WriteString(fmt.Sprintf("| %d | 🟢 %s | %s | `%s` |\n",
				r.Port, r.State, r.Service, banner))
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("## 🔒 No Open Ports Found\n\n")
		sb.WriteString("All scanned ports are closed or filtered.\n\n")
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Report generated by [PortScanGO](https://github.com/portscango)*\n")

	return os.WriteFile(filename, []byte(sb.String()), 0644)
}
